### ISSUE TITLE
Mysql2::Error: Field 'created_at' doesn't have a default value

### ISSUE THREAD

**Issue by warrick59** [8parth/make_model_searchable#1]
I do not specify attribute to searchable_attributes

**Comment by 8parth** [comment]
Can you provide more information? 
such as `created_at` field's type, which is usually datatime and search method added by gem won't search from `created_at` field.

**Comment by warrick59** [comment]
I will make you a demo app

**Comment by 8parth** [comment]
That would be very helpful !

**Comment by warrick59** [comment]
Here is the demo: https://github.com/warrick59/issue-make-search try to create a user, product or company, you have the error Mysql2::Error: Field 'created_at' doesn't have a default value

**Comment by 8parth** [comment]
@warrick59 Thanks for your help.. fixed.. Let me know if you face same issue again or some other issue.

**Comment by warrick59** [comment]
I will test and I would keep you informed, it was a pleasure to help you
